services:
  postgres:
    image: postgres:16-alpine
    container_name: base_fastapi_postgres
    environment:
      POSTGRES_USER: base_fastapi
      POSTGRES_PASSWORD: base_fastapi
      POSTGRES_DB: base_fastapi
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U base_fastapi"]
      interval: 5s
      timeout: 5s
      retries: 5
